# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/ice2603lab/lab_3new/lab_3new.srcs/sources_1/ip/lpm_ram_dq_dram/lpm_ram_dq_dram.xci
# IP: The module: 'lpm_ram_dq_dram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/ice2603lab/lab_3new/lab_3new.gen/sources_1/ip/lpm_ram_dq_dram/lpm_ram_dq_dram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lpm_ram_dq_dram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: f:/ice2603lab/lab_3new/lab_3new.srcs/sources_1/ip/lpm_ram_dq_dram/lpm_ram_dq_dram.xci
# IP: The module: 'lpm_ram_dq_dram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/ice2603lab/lab_3new/lab_3new.gen/sources_1/ip/lpm_ram_dq_dram/lpm_ram_dq_dram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lpm_ram_dq_dram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
