# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Computer_Orgnization_lab/BigWork/lab4_final/lab4_away.srcs/sources_1/ip/lpm_rom_irom/lpm_rom_irom.xci
# IP: The module: 'lpm_rom_irom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Computer_Orgnization_lab/BigWork/lab4_final/lab4_away.gen/sources_1/ip/lpm_rom_irom/lpm_rom_irom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lpm_rom_irom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Computer_Orgnization_lab/BigWork/lab4_final/lab4_away.srcs/sources_1/ip/lpm_rom_irom/lpm_rom_irom.xci
# IP: The module: 'lpm_rom_irom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Computer_Orgnization_lab/BigWork/lab4_final/lab4_away.gen/sources_1/ip/lpm_rom_irom/lpm_rom_irom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lpm_rom_irom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
