# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/ice2603lab/lab_2new/lab_2new.srcs/sources_1/ip/irom/irom.xci
# IP: The module: 'irom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/ice2603lab/lab_2new/lab_2new.gen/sources_1/ip/irom/irom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'irom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: f:/ice2603lab/lab_2new/lab_2new.srcs/sources_1/ip/irom/irom.xci
# IP: The module: 'irom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/ice2603lab/lab_2new/lab_2new.gen/sources_1/ip/irom/irom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'irom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
